"""GlassBox-BI Pydantic Schemas and API Contracts."""

from backend.app.schemas.health import HealthResponse
from backend.app.schemas.contracts import (
    DatasetMetadata,
    ForecastRequest,
    ForecastResult,
    ExplanationResult,
    RecommendationResult,
)
from backend.app.schemas.data_contract import (
    BusinessTimeSeriesRecord,
    ColumnMapping,
    DEFAULT_CANONICAL_MAPPING,
    SYNTHETIC_RETAIL_MAPPING,
    WALMART_MAPPING_TEMPLATE,
    ROSSMANN_MAPPING_TEMPLATE,
    auto_detect_column_mapping,
)
from backend.app.schemas.ingestion import (
    ValidationSeverity,
    ValidationIssue,
    QualityScoreBreakdown,
    TemporalLeakageReport,
    NumericSummary,
    DatasetProfile,
    IngestionResult,
)
from backend.app.schemas.processing import (
    MissingNumericStrategy,
    MissingCategoricalStrategy,
    MissingTargetStrategy,
    DuplicateStrategy,
    OutlierMethod,
    OutlierStrategy,
    DataProcessingConfig,
    ProcessingAuditEntry,
    TimeSeriesIntegrityReport,
    OutlierSummary,
    TemporalSplitMetadata,
    DataProcessingResult,
)

from backend.app.schemas.forecasting import (
    ForecastModelType,
    SelectionMetric,
    ForecastStatus,
    ForecastingConfig,
    ForecastPoint,
    ModelEvaluationScore,
    ModelSelectionResult,
    ModelMetadata,
)
from backend.app.schemas.evaluation import (
    EvaluationMetricType,
    EvaluationMetricResult,
    EvaluationPoint,
    ModelTestEvaluation,
    EvaluationRequest,
    BenchmarkResult,
)
from backend.app.schemas.explainability import (
    ExplanationMethod,
    ExplanationType,
    FeatureContribution,
    GlobalFeatureImportance,
    ExplanationFidelity,
    ExplanationAuditTrail,
    LocalExplanationRequest,
    GlobalExplanationRequest,
    ExplanationResult as FormalExplanationResult,
    MethodCompatibilityInfo,
    ExplainabilityConfigSchema,
)

__all__ = [
    "HealthResponse",
    "DatasetMetadata",
    "ForecastRequest",
    "ForecastResult",
    "ExplanationResult",
    "RecommendationResult",
    "BusinessTimeSeriesRecord",
    "ColumnMapping",
    "DEFAULT_CANONICAL_MAPPING",
    "SYNTHETIC_RETAIL_MAPPING",
    "WALMART_MAPPING_TEMPLATE",
    "ROSSMANN_MAPPING_TEMPLATE",
    "auto_detect_column_mapping",
    "ValidationSeverity",
    "ValidationIssue",
    "QualityScoreBreakdown",
    "TemporalLeakageReport",
    "NumericSummary",
    "DatasetProfile",
    "IngestionResult",
    "MissingNumericStrategy",
    "MissingCategoricalStrategy",
    "MissingTargetStrategy",
    "DuplicateStrategy",
    "OutlierMethod",
    "OutlierStrategy",
    "DataProcessingConfig",
    "ProcessingAuditEntry",
    "TimeSeriesIntegrityReport",
    "OutlierSummary",
    "TemporalSplitMetadata",
    "DataProcessingResult",
    "ForecastModelType",
    "SelectionMetric",
    "ForecastStatus",
    "ForecastingConfig",
    "ForecastPoint",
    "ModelEvaluationScore",
    "ModelSelectionResult",
    "ModelMetadata",
    "EvaluationMetricType",
    "EvaluationMetricResult",
    "EvaluationPoint",
    "ModelTestEvaluation",
    "EvaluationRequest",
    "BenchmarkResult",
    "ExplanationMethod",
    "ExplanationType",
    "FeatureContribution",
    "GlobalFeatureImportance",
    "ExplanationFidelity",
    "ExplanationAuditTrail",
    "LocalExplanationRequest",
    "GlobalExplanationRequest",
    "FormalExplanationResult",
    "MethodCompatibilityInfo",
    "ExplainabilityConfigSchema",
]


