"""Placeholder API Contracts for GlassBox-BI Modules.

These schemas define the communication boundaries between the Frontend,
FastAPI Backend, and future AI/Computational Modules.
NO forecasting, explanation, or recommendation logic is implemented here.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DatasetMetadata(BaseModel):
    """Contract for dataset metadata and cataloging (Phase 2+)."""
    dataset_id: str = Field(..., description="Unique dataset identifier")
    name: str = Field(..., description="Human-readable dataset name")
    filename: Optional[str] = Field(default=None, description="Original uploaded filename")
    row_count: Optional[int] = Field(default=None, ge=0, description="Total number of rows")
    column_count: Optional[int] = Field(default=None, ge=0, description="Total number of columns")
    timestamp_column: Optional[str] = Field(default=None, description="Name of the primary datetime column")
    target_column: Optional[str] = Field(default=None, description="Primary metric column to forecast")
    frequency: Optional[str] = Field(default=None, description="Inferred time-series frequency (e.g., 'D', 'W', 'M')")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Upload timestamp")


class ForecastRequest(BaseModel):
    """Contract for initiating a forecast task (Phase 4+)."""
    dataset_id: str = Field(..., description="Identifier of the ingested dataset to model")
    target_column: str = Field(..., description="Column name of the target variable to forecast")
    horizon: int = Field(default=30, ge=1, le=365, description="Number of future time steps to project")
    model_preference: Optional[str] = Field(default="auto", description="Model family preference: 'auto', 'statistical', 'ml'")
    confidence_level: float = Field(default=0.95, ge=0.5, le=0.99, description="Prediction interval confidence level")


class ForecastResult(BaseModel):
    """Contract for forecast outputs returned to frontend (Phase 4+)."""
    forecast_id: str = Field(..., description="Unique identifier for the forecast run")
    dataset_id: str = Field(..., description="Associated dataset identifier")
    horizon: int = Field(..., ge=1, description="Projection horizon length")
    model_name: str = Field(..., description="Name of the trained forecasting model")
    predictions: List[Dict[str, Any]] = Field(default_factory=list, description="List of forecast points with timestamps and values")
    confidence_intervals: Optional[Dict[str, Any]] = Field(default=None, description="Upper and lower prediction bounds")
    metrics: Optional[Dict[str, float]] = Field(default=None, description="Evaluation error metrics (MAE, RMSE, MAPE)")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Forecast completion timestamp")


class ExplanationResult(BaseModel):
    """Contract for explainability and feature attribution results (Phase 6+)."""
    explanation_id: str = Field(..., description="Unique explanation identifier")
    forecast_id: str = Field(..., description="Associated forecast run identifier")
    method: str = Field(default="shap", description="Interpretability methodology (e.g., 'shap', 'decomposition')")
    feature_attributions: Dict[str, float] = Field(default_factory=dict, description="Feature importance and attribution scores")
    decomposition: Optional[Dict[str, List[float]]] = Field(default=None, description="Decomposed trend, seasonality, and residual series")
    narrative_summary: Optional[str] = Field(default=None, description="Plain-language interpretation narrative generated by Explainability Agent")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Explanation generation timestamp")


class RecommendationResult(BaseModel):
    """Contract for decision intelligence insights and scenario recommendations (Phase 7+)."""
    recommendation_id: str = Field(..., description="Unique recommendation identifier")
    forecast_id: str = Field(..., description="Associated forecast run identifier")
    scenario_name: Optional[str] = Field(default="Baseline", description="Scenario simulation name")
    action_items: List[str] = Field(default_factory=list, description="Ranked prescriptive business actions")
    risk_assessment: Optional[str] = Field(default=None, description="Risk and volatility assessment")
    projected_impact: Optional[str] = Field(default=None, description="Estimated financial or KPI impact")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Recommendation timestamp")
