"""Placeholder API Contracts for GlassBox-BI Modules.

These schemas define the communication boundaries between the Frontend,
FastAPI Backend, and future AI/Computational Modules.
NO forecasting, explanation, or recommendation logic is implemented here.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class DatasetMetadata(BaseModel):
    """Contract for dataset metadata and cataloging (Phase 2+)."""
    dataset_id: str = Field(..., description="Unique dataset identifier")
    name: str = Field(..., description="Human-readable dataset name")
    filename: Optional[str] = Field(default=None, description="Original uploaded filename")
    row_count: Optional[int] = Field(default=None, ge=0, description="Total number of rows")
    column_count: Optional[int] = Field(default=None, ge=0, description="Total number of columns")
    timestamp_column: Optional[str] = Field(default=None, description="Name of the primary datetime column")
    target_column: Optional[str] = Field(default=None, description="Primary metric column to forecast")
    frequency: Optional[str] = Field(default=None, description="Inferred time-series frequency (e.g., 'D', 'W', 'M')")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Upload timestamp")


from backend.app.schemas.forecasting import ForecastRequest, ForecastResult


class ExplanationResult(BaseModel):
    """Contract for explainability and feature attribution results (Phase 6+)."""
    explanation_id: str = Field(..., description="Unique explanation identifier")
    forecast_id: str = Field(..., description="Associated forecast run identifier")
    method: str = Field(default="shap", description="Interpretability methodology (e.g., 'shap', 'decomposition')")
    feature_attributions: Dict[str, float] = Field(default_factory=dict, description="Feature importance and attribution scores")
    decomposition: Optional[Dict[str, List[float]]] = Field(default=None, description="Decomposed trend, seasonality, and residual series")
    narrative_summary: Optional[str] = Field(default=None, description="Plain-language interpretation narrative generated by Explainability Agent")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Explanation generation timestamp")


class RecommendationResult(BaseModel):
    """Contract for decision intelligence insights and scenario recommendations (Phase 7+)."""
    recommendation_id: str = Field(..., description="Unique recommendation identifier")
    forecast_id: str = Field(..., description="Associated forecast run identifier")
    scenario_name: Optional[str] = Field(default="Baseline", description="Scenario simulation name")
    action_items: List[str] = Field(default_factory=list, description="Ranked prescriptive business actions")
    risk_assessment: Optional[str] = Field(default=None, description="Risk and volatility assessment")
    projected_impact: Optional[str] = Field(default=None, description="Estimated financial or KPI impact")
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc), description="Recommendation timestamp")
